---
- name: Install dependencies for itself
  apt:
    name:
      - python3-apt
      - python3-pip
      - git
    state: present
    update_cache: true

- name: Check if Lighthouse directory already exists
  stat:
    path: /opt/lighthouse
  register: lighthouse_dir

- name: Clone Lighthouse repository
  git:
    repo: 'https://github.com/VKCOM/lighthouse.git'
    dest: '/opt/lighthouse'
    version: master
  when: not lighthouse_dir.stat.exists

- name: Change ownership of Lighthouse directory
  file:
    path: /opt/lighthouse
    owner: www-data
    group: www-data
    recurse: true
    state: directory

- name: Generate Nginx configuration for Lighthouse
  template:
    src: lighthouse_nginx_config.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: "0644"
  notify: Restart nginx service

- name: Delete nginx default configuration file if exists
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx service
